version: '3.4'
networks:
  dusi:

services:
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"
    networks:
      - dusi

  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"

  api:
    image: dusi-api:latest
    build:
      context: .
      dockerfile: src/Http.API/Dockerfile
    environment:
      - "ConnectionStrings__Default=Server=192.168.31.193;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dusi
    ports:
      - "50002:50001"
      - "5200:80"
      
  api-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","api",
        "-app-port","80",
        "-placement-host-address","placement:50000",
        "-components-path","/components",
        "-enable-api-logging","true",
        "-config", "/dusi-config.yaml"
      ]
    volumes:
      - "./scripts/components/:/components"
      - "./scripts/dusi-config.yaml:/dusi-confg.yaml"

    depends_on:
      - api
    network_mode: "service:api"

  task:
    image: dusi-task:latest
    environment:
      - "ConnectionStrings__Default=Server=192.168.31.193;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/Microservices/TaskService/Dockerfile
    networks:
      - dusi
    ports:
      - "50003:50001"
      - "5201:80"
      
  task-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","task",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./scripts/components/:/components"
    depends_on:
      - task
    network_mode: "service:task"

  cms:
    image: dusi-cms:latest
    environment:
      - "ConnectionStrings__Default=Server=192.168.31.193;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    build:
      context: .
      dockerfile: src/Microservices/CMSService/Dockerfile
    networks:
      - dusi
    ports:
      - "50004:50001"
      - "5202:80"
      - "443" 

  cms-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","cms",
        "-app-port","443",
        "-app-ssl","true",
        "-app-protocol","grpc",
        "-placement-host-address","placement:50000",
        "-components-path","/components",
        "-enable-api-logging","true",
        "-config", "/dusi-config.yaml"
      ]
    volumes:
      - "./scripts/components/:/components"
      - "./scripts/dusi-config.yaml:/dusi-confg.yaml"
    depends_on:
      - cms
    network_mode: "service:cms"

