version: '3.4'
networks:
  dusi:

services:
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dusi

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    networks:
      - dusi

  api:
    image: dusi-api:latest
    build:
      context: .
      dockerfile: src/Http.API/Dockerfile
    environment:
      - "ConnectionStrings__Default=Server=localhost;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - redis
      - placement
    networks:
      - dusi
    ports:
      - "5200:80"
      
  api-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "api",
        "-app-port",
        "5200",
        "-placement-host-address",
        "placement:50006",
        "-dapr-grpc-port",
        "50002",
        "-components-path",
        "/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - api
    network_mode: "service:api"

  task:
    image: dusi-task:latest
    environment:
      - "ConnectionStrings__Default=Server=localhost;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/Microservices/TaskService/Dockerfile
    depends_on:
      - redis
      - placement
    networks:
      - dusi
    ports:
      - "5201:80"
      
  task-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "task",
        "-app-port",
        "5201",
        "-placement-host-address",
        "placement:50006",
        "-dapr-grpc-port",
        "50003",
        "-components-path",
        "/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - task
    network_mode: "service:task"

  cms:
    image: dusi-cms:latest
    environment:
      - "ConnectionStrings__Default=Server=localhost;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/Microservices/CMSService/Dockerfile
    depends_on:
      - redis
      - placement
    networks:
      - dusi
    ports:
      - "5202:80"
      
  cms-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "cms",
        "-app-port",
        "5202",
        "-placement-host-address",
        "placement:50006",
        "-dapr-grpc-port",
        "50004",
        "-components-path",
        "/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - cms
    network_mode: "service:cms"

