version: '3.4'
networks:
  dusi:

services:
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50000"]
    ports:
      - "50000:50000"
    networks:
      - dusi

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    networks:
      - dusi

  api:
    image: dusi-api:latest
    build:
      context: .
      dockerfile: src/Http.API/Dockerfile
    environment:
      - "ConnectionStrings__Default=Server=192.168.5.65;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - redis
    networks:
      - dusi
    ports:
      - "50002:50001"
      - "5200:80"
      
  api-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","api",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - api
    network_mode: "service:api"

  task:
    image: dusi-task:latest
    environment:
      - "ConnectionStrings__Default=Server=192.168.5.65;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/Microservices/TaskService/Dockerfile
    depends_on:
      - redis
    networks:
      - dusi
    ports:
      - "50003:50001"
      - "5201:80"
      
  task-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","task",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - task
    network_mode: "service:task"

  cms:
    image: dusi-cms:latest
    environment:
      - "ConnectionStrings__Default=Server=192.168.5.65;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/Microservices/CMSService/Dockerfile
    depends_on:
      - redis
    networks:
      - dusi
    ports:
      - "50004:50001"
      - "5202:80"
      
  cms-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","cms",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - cms
    network_mode: "service:cms"

