version: '3.4'

networks:
  dusi:

services:
  redis:
    image: redis:7-alpine
    networks:
      - dusi
    ports:
      - "6379:6379"

  api:
    image: ghcr.io/aterdev/dusi-api:latest
    environment:
      - "ConnectionStrings__Default=Server=localhost;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
    networks:
      - dusi
    ports:
      - "50002:50001"
      - "5200:80"
      
  api-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","api",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - redis
      - api
    network_mode: "service:api"

  task:
    image: ghcr.io/aterdev/dusi-task:latest
    environment:
      - "ConnectionStrings__Default=Server=localhost;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
    networks:
      - dusi
    ports:
      - "50003:50001"
      - "5201:80"
      
  task-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","task",
        "-app-portd","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - redis
      - task
    network_mode: "service:task"

  cms:
    image: ghcr.io/aterdev/dusi-cms:latest
    environment:
      - "ConnectionStrings__Default=Server=localhost;Port=5432;Database=dusi.dev;User Id=postgres;Password=root;"
    networks:
      - dusi
    ports:
      - "50004:50001"
      - "5202:80"
      - "443" 
      
  cms-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id","cms",
        "-app-port","443",
        "-app-protocol","grpc",
        "-components-path","/components",
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - redis
      - cms
    network_mode: "service:cms"

