version: '3.4'

networks:
  dusi:

services:
  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - dusi
    ports:
      - "6379:6379"

  api:
    image: ghcr.io/aterdev/dusi-api:latest
    container_name: dusi_api
    restart: always
    volumes:
      - "/data/web/markdown:/app/wwwroot/markdown"
      - "/data/web/blogs:/app/wwwroot/blogs"
    environment:
      - AppConfig=${AppConfig}

    networks:
      - dusi
    depends_on:
      - redis
    ports:
      - "50002:50001"
      - "5200:80"
      
  api-dapr:
    image: "daprio/daprd:edge"
    restart: always
    command:
      [
        "./daprd",
        "-app-id","api",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - redis
      - api
    network_mode: "service:api"

  task:
    image: ghcr.io/aterdev/dusi-task:latest
    container_name: dusi_task
    restart: always
    networks:
      - dusi
    environment:
      - AppConfig=${AppConfig}
    depends_on:
      - redis      
    ports:
      - "50003:50001"
      - "5201:80"
      
  task-dapr:
    image: "daprio/daprd:edge"
    restart: always
    command:
      [
        "./daprd",
        "-app-id","task",
        "-app-port","80",
        "-components-path","/components"
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - redis
      - task
    network_mode: "service:task"