name: Update CMS Service
on:
  push:
    branches: [ "prod" ]
    paths:
      - "src/Microservices/CMSService/**"
      # - "src/Application/**"
      # - "src/Share/**"
      # - "src/Core/**"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        registry: ghcr.io
        username: niltor
        password: ${{ vars.PAT }}

    - name: Build the Docker image
      run: |
        docker build -f ./src/Microservices/CMSService/Dockerfile -t dusi-cms:latest ./

    - name: docker tag & push
      run: |
        docker tag dusi-cms:latest ghcr.io/aterdev/dusi-cms:latest
        
        docker push ghcr.io/aterdev/dusi-cms:latest

