name: Docker Image CI

on:
  push:
    branches: [ "prod" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        PAT: ${{ secrets.PAT }}
      run: echo "$PAT"
      
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        registry: ghcr.io
        username: niltor
        password: "$PAT"

    - name: Build the Docker image
      run: |
        docker build -f ./src/Http.API/Dockerfile -t dusi-api:latest ./
        docker build -f ./src/Microservices/TaskService/Dockerfile -t dusi_task:latest ./
        docker build -f ./src/Microservices/CMSService/Dockerfile -t dusi_cms:latest ./

    - name: docker push
      run: |
        docker tag dusi-api:latest ghcr.io/aterdev/dusi-api:latest
        docker tag dusi_task:latest ghcr.io/aterdev/dusi_task:latest
        docker tag dusi_cms:latest ghcr.io/aterdev/dusi_cms:latest
