name: Update Task Service
on:
  push:
    branches: [ "prod" ]
    paths:
      - "src/Microservices/TaskService/**"
      - "src/Application/**"
      - "src/Share/**"
      - "src/Core/**"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        registry: ghcr.io
        username: niltor
        password: ${{ vars.PAT }}

    - name: Build the Docker image
      run: |
        docker build -f ./src/Microservices/TaskService/Dockerfile -t dusi-task:latest ./

    - name: docker tag & push
      run: |
        docker tag dusi-task:latest ghcr.io/aterdev/dusi-task:latest
        docker push ghcr.io/aterdev/dusi-task:latest

    - name: SSH Execute Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /data/run
          docker-compose pull task
          docker-compose -p dusi up -d 
          docker-compose -p dusi restart task-dapr
          docker rmi $(docker images -f "dangling=true" -q)
        debug: true